[mypy]
python_version = 3.12
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_optional = True
check_untyped_defs = True
disallow_untyped_defs = True

[mypy-spacetrack.*]
ignore_missing_imports = True

[mypy-sgp4.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True
