"""Real Conjunction Data Messages (CDMs) from Space-Track.

Unlike the SGP4-based screening in propagator.py/screener.py, which
computes its own miss-distance estimate from public TLEs, this pulls the
actual operational product: CDMs generated by 18th Space Defense
Squadron using their full-fidelity ephemerides and covariance data.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any

from spacetrack import SpaceTrackClient


@dataclass(frozen=True)
class CDMEvent:
    cdm_id: str
    tca: datetime
    miss_distance_km: float
    collision_probability: float | None
    primary_name: str
    secondary_name: str
    primary_norad_id: int | None
    secondary_norad_id: int | None


def _first_present(row: dict[str, Any], *keys: str) -> Any | None:
    for key in keys:
        if key in row and row[key] not in (None, ""):
            return row[key]
    return None


def _parse_miss_distance_km(row: dict[str, Any]) -> float:
    raw = _first_present(row, "MISS_DISTANCE")
    if raw is None:
        return float("nan")
    value = float(raw)
    unit = (_first_present(row, "MISS_DISTANCE_UNIT") or "m").lower()
    return value / 1000.0 if unit == "m" else value


def _parse_probability(row: dict[str, Any]) -> float | None:
    raw = _first_present(row, "COLLISION_PROBABILITY", "PC")
    return float(raw) if raw is not None else None


def _parse_norad_id(row: dict[str, Any], *keys: str) -> int | None:
    raw = _first_present(row, *keys)
    try:
        return int(raw) if raw is not None else None
    except (TypeError, ValueError):
        return None


def _parse_row(row: dict[str, Any]) -> CDMEvent:
    tca_raw = _first_present(row, "TCA")
    tca = datetime.fromisoformat(tca_raw) if tca_raw else datetime.min

    return CDMEvent(
        cdm_id=str(_first_present(row, "CDM_ID") or ""),
        tca=tca,
        miss_distance_km=_parse_miss_distance_km(row),
        collision_probability=_parse_probability(row),
        primary_name=str(
            _first_present(row, "SAT1_OBJECT_NAME", "SAT_1_NAME") or "UNKNOWN"
        ),
        secondary_name=str(
            _first_present(row, "SAT2_OBJECT_NAME", "SAT_2_NAME") or "UNKNOWN"
        ),
        primary_norad_id=_parse_norad_id(
            row, "SAT1_OBJECT_DESIGNATOR", "SAT_1_ID", "SAT1_NORAD_CAT_ID"
        ),
        secondary_norad_id=_parse_norad_id(
            row, "SAT2_OBJECT_DESIGNATOR", "SAT_2_ID", "SAT2_NORAD_CAT_ID"
        ),
    )


def fetch_recent_cdms(
    client: SpaceTrackClient,
    norad_id: int,
    lookback_days: int = 7,
    limit: int = 50,
) -> list[CDMEvent]:
    """Fetch real CDMs issued for `norad_id` in the last `lookback_days`."""
    rows = client.cdm(
        message_for=norad_id,
        creation_date=f">now-{lookback_days}",
        orderby="tca desc",
        limit=limit,
    )
    return [_parse_row(dict(row)) for row in rows]